version: '2'
services:
  memyshelfandi-app:
    image: memyshelfandi
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_COUCHBASE_BOOTSTRAP_HOSTS=memyshelfandi-couchbase
      - SPRING_COUCHBASE_BUCKET_NAME=MeMyshelfAndI
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8082:8082
  memyshelfandi-couchbase:
    extends:
      file: couchbase.yml
      service: memyshelfandi-couchbase
